name: Build Sample APK

on:
  workflow_dispatch: # run manually from GitHub Actions tab
  push:              # also run on every push to main/master
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build sample debug APK
        run: ./gradlew :sample:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chucker-Sample-APK
          path: sample/build/outputs/apk/debug/*.apk
